### ISSUE TITLE
Porque não fazer este repo como clone do original?

### ISSUE THREAD

**Issue by camilohollanda** [wirecardBrasil/moip-sdk-js#2]

**Comment by brunoosilva** [comment]
Uma boa idéia, mas o pessoal na Moip é um pouco devagar, e os jobs não espera haha.

**Comment by prem-prakash** [comment]
sim, mas quando o repo fica como clone pelo menos eles podem comparar de forma mais fácil, e podemos abrir um PR de cá pra lá, para ajudá-los na lentidão deles
