### ISSUE TITLE
Validação de novas bandeiras

### ISSUE THREAD

**Issue by mprandot** [wirecardBrasil/moip-sdk-js#20]
Fala pessoal! Tudo bem com vocês?

Estou necessitando validar as bandeiras PRESTO e MAGNA, não encontrei nada sobre na doc, sabem me informar se a biblioteca tem suporte para essas bandeiras? Caso não, há como adicionar de forma dinâmica?

Exemplos do mercado pago:

Magna - 5680 0887 8727 1080
Presto - 9200 6750 5403 7716

Obrigado!

**Comment by somentelucas** [comment]
Oi @mprandot, a biblioteca não tem suporte para essas bandeiras, visto que a Wirecard ainda não as aceita. Se você quiser, pode ficar à vontade para abrir uma pull request para validá-las!

Abraços!
